### ISSUE TITLE
Add sniff to detect `get_option`/`update_option` usage with prefix in name (`wpseo_`)

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoastcs#222] opened 2020-08-14 12:01 UTC
We have our own `WPSEO_Options` framework. This should be used for all interactions with options.
So any calls to `get_option` or `update_option` with a specific prefix should result in an error in the sniffs.

Whenever we want to allow these specifically, sniff-excludes should be used to mark them.

**Comment by jrfnl** [comment] 2023-09-22 08:56
Closing as duplicate of #69

**Closed as not planned by jrfnl** 2023-09-22 08:56 UTC
Labels: Status: duplicate
